baseurl = "http://localhost"
languageCode = "en-us"
title = "Elchwald"

[Params]
  github = "sahib"
  email = "sahib@online.de"
  description = "Personal page of Chris Pahl ğŸ‘¨ and his software â¤"
  # cover = "/brig.png"
  logo = "/images/geweih.svg"
